name: Update RSS Feed

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        env:
          FB_EMAIL: ${{ secrets.FB_EMAIL }}
          FB_PASSWORD: ${{ secrets.FB_PASSWORD }}
        run: python fetch.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add feeds/
          git commit -m "Auto-update feeds every 15 minutes" || exit 0
          git push
